name: Nginx Static

on:
  push:
    paths:
      - 'nginx-static/*'
      - '.github/workflows/nginx-static.yml'

jobs:

  build-nginx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: nginx-static
        registry: ghcr.io
        context: nginx-static
