name: Nginx Static

on:
  push:
    paths:
      - 'nginx-static/*'
      - '.github/workflows/nginx-static.yml'

jobs:

  build:

    name: Build docker image (with cache) and push it to registry
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - uses: prosperity-tech/docker-build-with-cache-action@master
      with:
        username: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        password: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        image_name: nginx-static
        registry: 861729690598.dkr.ecr.us-west-1.amazonaws.com
        context: nginx-static
